apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: python.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-python-service
            port:
              number: 8000
  - host: dart.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-dart-service
            port:
              number: 8080